### ISSUE TITLE
Detection options

### ISSUE THREAD

**Issue by 1ForeverHD** [1ForeverHD/ZonePlus#17]
- [x] setup an enum 'Detection' with members 'Automatic', 'WholeBody' and 'Centre'
- [x] for enums, have it so you can do ``enum = Zone.enum.EnumName.EnumMember``
- [x] convert others enums to do this
- [x] property ``zone.enterDetection = Zone.enum.Detection.Automatic``
- [x] property ``zone.exitDetection = Zone.enum.Detection.Automatic``
- [x] property ``zone._currentEnterDetection = zone.enterDetection``
- [x] property ``zone._currentExitDetection = zone.enterDetection``
- [x] method ``zone:setDetection(detectionName, enterOrExitOrBoth)``
- [x] Consider moving all of above to ZoneController
- [x] reconfigure the following so they differ depending upon _currentEnter/ExitDetection
  - [x] players (localplayer and player), events and methods
  - [ ] parts (touch triggers), events and methods
- [x] run some tests to see the maximum volume size rotatedregion3 can comfortably work with. set a constant property
- [x] dynamically change ._current to centre (if above) or wholebody (if below) BUT consider how this works for part volumes???
- [x] dynamically adapy for
  - [x] players
  - [ ] parts
- [x] update docs
  - [x] zone API enter and exit detection properties
  - [ ] methodology and explain the automatic system
- [x] let Lobestone and R_alatch know of update

**Comment by Solarizator-Inc** [comment]
`thx yay`
