### ISSUE TITLE
Zone:_partTouchedZone(part) is not used

### ISSUE THREAD

**Issue by Scyfren** [1ForeverHD/ZonePlus#20]
I was looking through the code for partExited and partEntered and I found that Zone:_partTouchedZone(part) was not used. Is the feature still a work in progress?

**Comment by 1ForeverHD** [comment]
It's used for line 272:

https://i.imgur.com/opfLKx4.png

We've designed it this way to make it scalable for player events once .CanTouch goes live (and proves to be effective).
