### ISSUE TITLE
API reference mix up two functions names

### ISSUE THREAD

**Issue by Jaguar-515** [1ForeverHD/ZonePlus#23]
The API documentation for Zone+ seems to mix up two functions name, which makes it confusing for new users who read the API documentation and get confused on why their code doesn't seem to be working when copied from the example code snippets.

* [playerEntered](https://1foreverhd.github.io/ZonePlus/api/zone/#playerentered) should be playerAdded
* [playerExited](https://1foreverhd.github.io/ZonePlus/api/zone/#playerexited) should be playerRemoving

Was this intentional or not?

**Comment by optimisticside** [comment]
`playerEntered` and `playerExited` are custom events part of the `Zone` class and don't have anything to do with the `Player` service's `PlayerAdded` and `PlayerRemoving` events.
