### ISSUE TITLE
Spelling mistake in documentation

### ISSUE THREAD

**Issue by SteadyStudio** [1ForeverHD/ZonePlus#37]
Hey there, found a little spelling mistake in the API reference section.

![image](https://user-images.githubusercontent.com/87199833/146645490-02564f9d-bab7-4374-b025-b609c9071955.png)

I'm pretty sure it's supposed to be "Constructors", not "Construtors"

**Comment by 1ForeverHD** [comment]
Good spot thanks! It looks like this mistake was also copied into TopbarPlus so we'll fix it there too. I've updated them locally and then they'll be pushed up alongside the next releases for both projects.
