### ISSUE TITLE
partEvents do not fire if the character is destroyed inside

### ISSUE THREAD

**Issue by 1ForeverHD** [1ForeverHD/ZonePlus#53]
e.g. ``workspace.ForeverHD:Destroy()``

they do however work for ``player`` and ``item`` events.

more details here: https://devforum.roblox.com/t/zoneplus-v320-construct-dynamic-zones-and-effectively-determine-players-and-parts-within-their-boundaries/1017701/383?u=foreverhd

**Comment by Argus74** [comment]
Hello, I would like to contribute to repository. Is this issue open?
